export default [
  {
    type: "SC",
    name: "Scout",
    firstTokenIndex: 1,
    noOfTokens: 6,
    cost: 6,
    hull: 1,
    upkeepCost: 1,
    availableTechs: [
      "Point Def 1",
      "Point Def 2",
      "Point Def 3",
    ],
  },
  {
    type: "SCX",
    name: "Scout-X",
    firstTokenIndex: 7,
    noOfTokens: 1,
    cost: 6,
    hull: 1,
    upkeepCost: 1,
    availableTechs: [
      "Point Def 1",
      "Point Def 2",
      "Point Def 3",
    ],
  },
  {
    type: "DD",
    name: "Destroyer",
    firstTokenIndex: 1,
    noOfTokens: 6,
    cost: 9,
    hull: 1,
    upkeepCost: 1,
    availableTechs: [
      "DDX",
      "Scanner 1",
      "Scanner 2",
      "Fast 2",
    ],
  },
  {
    type: "CA",
    name: "Cruiser",
    firstTokenIndex: 1,
    noOfTokens: 6,
    cost: 12,
    hull: 2,
    upkeepCost: 2,
    availableTechs: [
      "Exploration 1",
      "Exploration 2",
    ],
  },
  {
    type: "BC",
    name: "Battlecruiser",
    firstTokenIndex: 1,
    noOfTokens: 6,
    cost: 15,
    hull: 2,
    upkeepCost: 2,
    availableTechs: [
      "Fast 1",
    ],
  },
  {
    type: "BB",
    name: "Battleship",
    firstTokenIndex: 1,
    noOfTokens: 6,
    cost: 20,
    hull: 3,
    upkeepCost: 3,
    availableTechs: [
      "Tractor Beam",
    ],
  },
  {
    type: "DN",
    name: "Dreadnaught",
    firstTokenIndex: 1,
    noOfTokens: 5,
    cost: 24,
    hull: 3,
    upkeepCost: 3,
    availableTechs: [
      "Shield Proj.",
    ],
  },
  {
    type: "TN",
    name: "Titan",
    firstTokenIndex: 1,
    noOfTokens: 5,
    cost: 32,
    hull: 5,
    upkeepCost: 5,
    availableTechs: [
      "Fighters",
    ],
  },
  {
    type: "Base",
    name: "Base",
    firstTokenIndex: 1,
    noOfTokens: 4,
    cost: 12,
    hull: 3,
    upkeepCost: 0,
    availableTechs: [
      "Exploration 2",
      "Scanner 1",
      "Scanner 2",
    ],
  },
  {
    type: "Decoy",
    name: "Decoy",
    firstTokenIndex: 1,
    noOfTokens: 4,
    cost: 1,
    hull: 0,
    upkeepCost: 0,
    availableTechs: [
    ],
  },
  {
    type: "Miner",
    name: "Mining Ship",
    firstTokenIndex: 1,
    noOfTokens: 4,
    cost: 5,
    hull: 1,
    upkeepCost: 0,
    availableTechs: [
      "Terraforming 2",
    ],
  },
  {
    type: "MinerX",
    name: "Mining Ship",
    firstTokenIndex: 5,
    noOfTokens: 4,
    cost: 5,
    hull: 1,
    upkeepCost: 0,
    availableTechs: [
      "Terraforming 2",
    ],
  },
  {
    type: "SY",
    name: "Ship Yard",
    firstTokenIndex: 1,
    noOfTokens: 7,
    cost: 6,
    hull: 1,
    upkeepCost: 0,
    availableTechs: [
      "Exploration 2",
    ],
  },
  {
    type: "T",
    name: "Transport",
    firstTokenIndex: 1,
    noOfTokens: 6,
    cost: 6,
    hull: 1,
    upkeepCost: 1,
    availableTechs: [
      "Anti-Replicator",
      "Drop Ship",
    ],
  },
  {
    type: "Inf",
    name: "Infantry",
    firstTokenIndex: 1,
    noOfTokens: 10,
    cost: 2,
    hull: 1,
    upkeepCost: 0,
    availableTechs: [
    ],
  },
  {
    type: "Mar",
    name: "Space Marines",
    firstTokenIndex: 1,
    noOfTokens: 8,
    cost: 3,
    hull: 2,
    upkeepCost: 0,
    availableTechs: [
    ],
  },
  {
    type: "HI",
    name: "Heave Infantry",
    firstTokenIndex: 1,
    noOfTokens: 10,
    cost: 3,
    hull: 2,
    upkeepCost: 0,
    availableTechs: [
    ],
  },
  {
    type: "Grav",
    name: "Grav Armor",
    firstTokenIndex: 1,
    noOfTokens: 6,
    cost: 4,
    hull: 2,
    upkeepCost: 0,
    availableTechs: [
    ],
  },
  {
    type: "BD",
    name: "Boarding Ship",
    firstTokenIndex: 1,
    noOfTokens: 6,
    cost: 12,
    hull: 2,
    upkeepCost: 2,
    availableTechs: [
      "Boarding 2",
    ],
  },
  {
    type: "R",
    name: "Raider",
    firstTokenIndex: 1,
    noOfTokens: 6,
    cost: 12,
    hull: 2,
    upkeepCost: 2,
    availableTechs: [
      "RX",
      "Cloaking 2",
      "Fast 2",
      "Drop Ship",
    ],
  },
  {
    type: "CV",
    name: "Carrier",
    firstTokenIndex: 1,
    noOfTokens: 6,
    cost: 12,
    hull: 1,
    upkeepCost: 1,
    availableTechs: [
    ],
  },
  {
    type: "BV",
    name: "Battle Carrier",
    firstTokenIndex: 1,
    noOfTokens: 6,
    cost: 20,
    hull: 3,
    upkeepCost: 3,
    availableTechs: [
      "Fast 2",
    ],
  },
  {
    type: "F",
    name: "Fighter",
    firstTokenIndex: 1,
    noOfTokens: 10,
    cost: 5,
    hull: 1,
    upkeepCost: 1,
    availableTechs: [
      "Fighters 2",
      "Fighters 3",
      "Fighters 4",
    ],
  },
  {
    type: "Mines",
    name: "Mines",
    firstTokenIndex: 1,
    noOfTokens: 9,
    cost: 5,
    hull: 1,
    upkeepCost: 0,
    availableTechs: [
    ],
  },
  {
    type: "SW",
    name: "Mine Sweeper",
    firstTokenIndex: 1,
    noOfTokens: 6,
    cost: 6,
    hull: 1,
    upkeepCost: 1,
    availableTechs: [
      "Mine Sweeper 2",
      "Mine Sweeper 3",
    ],
  },
  {
    type: "FLAG",
    name: "Flagship",
    firstTokenIndex: 1,
    noOfTokens: 1,
    cost: 0,
    hull: 3,
    upkeepCost: 0,
    availableTechs: [
      "Exploration 1",
      "Exploration 2",
      "Fast BC",
    ],
  },
];